version: '3'

services:
  nats-streaming:
    image: nats-streaming
    ports:
      - '4222:4222'
      - '8222:8222'
    volumes:
      - ./nats-streaming-config.conf:/etc/nats-streaming/nats-streaming-config.conf
      - ./datastore:/datastore
    networks:
      - my-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: My_user
      POSTGRES_PASSWORD: 1234554321
      POSTGRES_DB: My_db
    ports:
      - '5432:5432'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    command:
      - 'postgres'
      - '-c'
      - 'log_statement=all'
    networks:
      my-network:
        ipv4_address: 172.19.0.2 

  go-server:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - nats-streaming
      - postgres
    networks:
      - my-network

networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
